// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Grammar",
			pos:  position{line: 17, col: 1, offset: 109},
			expr: &actionExpr{
				pos: position{line: 17, col: 11, offset: 121},
				run: (*parser).callonGrammar1,
				expr: &seqExpr{
					pos: position{line: 17, col: 11, offset: 121},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 17, col: 11, offset: 121},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 17, col: 14, offset: 124},
							label: "statements",
							expr: &zeroOrMoreExpr{
								pos: position{line: 17, col: 25, offset: 135},
								expr: &seqExpr{
									pos: position{line: 17, col: 27, offset: 137},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 17, col: 27, offset: 137},
											name: "Statement",
										},
										&ruleRefExpr{
											pos:  position{line: 17, col: 37, offset: 147},
											name: "__",
										},
									},
								},
							},
						},
						&choiceExpr{
							pos: position{line: 17, col: 44, offset: 154},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 17, col: 44, offset: 154},
									name: "EOF",
								},
								&ruleRefExpr{
									pos:  position{line: 17, col: 50, offset: 160},
									name: "SyntaxError",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 22, col: 1, offset: 212},
			expr: &ruleRefExpr{
				pos:  position{line: 22, col: 13, offset: 226},
				name: "ModelDefine",
			},
		},
		{
			name: "ModelDefine",
			pos:  position{line: 24, col: 1, offset: 240},
			expr: &actionExpr{
				pos: position{line: 24, col: 16, offset: 257},
				run: (*parser).callonModelDefine1,
				expr: &seqExpr{
					pos: position{line: 24, col: 16, offset: 257},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 24, col: 16, offset: 257},
							val:        "model",
							ignoreCase: false,
							want:       "\"model\"",
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 24, offset: 265},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 24, col: 26, offset: 267},
							label: "ident",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 32, offset: 273},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 43, offset: 284},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 24, col: 45, offset: 286},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 49, offset: 290},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 24, col: 52, offset: 293},
							label: "selectData",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 63, offset: 304},
								name: "Select",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 70, offset: 311},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 24, col: 73, offset: 314},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "Select",
			pos:  position{line: 29, col: 1, offset: 362},
			expr: &actionExpr{
				pos: position{line: 29, col: 10, offset: 373},
				run: (*parser).callonSelect1,
				expr: &seqExpr{
					pos: position{line: 29, col: 10, offset: 373},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 29, col: 10, offset: 373},
							val:        "select",
							ignoreCase: false,
							want:       "\"select\"",
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 19, offset: 382},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 22, offset: 385},
							label: "fieldList",
							expr: &ruleRefExpr{
								pos:  position{line: 29, col: 32, offset: 395},
								name: "SelectFieldList",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 48, offset: 411},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 29, col: 51, offset: 414},
							val:        "from",
							ignoreCase: false,
							want:       "\"from\"",
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 58, offset: 421},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 61, offset: 424},
							label: "model",
							expr: &ruleRefExpr{
								pos:  position{line: 29, col: 67, offset: 430},
								name: "Model",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 73, offset: 436},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 76, offset: 439},
							label: "join",
							expr: &zeroOrOneExpr{
								pos: position{line: 29, col: 81, offset: 444},
								expr: &ruleRefExpr{
									pos:  position{line: 29, col: 81, offset: 444},
									name: "JoinClause",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 93, offset: 456},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 29, col: 96, offset: 459},
							label: "where",
							expr: &zeroOrOneExpr{
								pos: position{line: 29, col: 102, offset: 465},
								expr: &ruleRefExpr{
									pos:  position{line: 29, col: 102, offset: 465},
									name: "WhereClause",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 29, col: 115, offset: 478},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "SelectFieldList",
			pos:  position{line: 33, col: 1, offset: 540},
			expr: &seqExpr{
				pos: position{line: 33, col: 19, offset: 560},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 33, col: 19, offset: 560},
						name: "SelectField",
					},
					&ruleRefExpr{
						pos:  position{line: 33, col: 32, offset: 573},
						name: "__",
					},
					&zeroOrMoreExpr{
						pos: position{line: 33, col: 35, offset: 576},
						expr: &seqExpr{
							pos: position{line: 33, col: 37, offset: 578},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 33, col: 37, offset: 578},
									val:        ",",
									ignoreCase: false,
									want:       "\",\"",
								},
								&ruleRefExpr{
									pos:  position{line: 33, col: 41, offset: 582},
									name: "__",
								},
								&ruleRefExpr{
									pos:  position{line: 33, col: 44, offset: 585},
									name: "SelectField",
								},
								&ruleRefExpr{
									pos:  position{line: 33, col: 56, offset: 597},
									name: "__",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Model",
			pos:  position{line: 34, col: 1, offset: 602},
			expr: &ruleRefExpr{
				pos:  position{line: 34, col: 9, offset: 612},
				name: "Identifier",
			},
		},
		{
			name: "SelectField",
			pos:  position{line: 35, col: 1, offset: 624},
			expr: &actionExpr{
				pos: position{line: 35, col: 15, offset: 640},
				run: (*parser).callonSelectField1,
				expr: &seqExpr{
					pos: position{line: 35, col: 15, offset: 640},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 35, col: 15, offset: 640},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 35, col: 21, offset: 646},
								name: "SelectFieldIdentifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 35, col: 45, offset: 670},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 35, col: 48, offset: 673},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 35, col: 54, offset: 679},
								expr: &seqExpr{
									pos: position{line: 35, col: 55, offset: 680},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 35, col: 55, offset: 680},
											val:        "as",
											ignoreCase: false,
											want:       "\"as\"",
										},
										&ruleRefExpr{
											pos:  position{line: 35, col: 60, offset: 685},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 35, col: 64, offset: 689},
											name: "Identifier",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SelectFieldIdentifier",
			pos:  position{line: 39, col: 1, offset: 746},
			expr: &choiceExpr{
				pos: position{line: 39, col: 26, offset: 773},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 39, col: 26, offset: 773},
						val:        "*",
						ignoreCase: false,
						want:       "\"*\"",
					},
					&ruleRefExpr{
						pos:  position{line: 39, col: 32, offset: 779},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "JoinClause",
			pos:  position{line: 45, col: 1, offset: 796},
			expr: &seqExpr{
				pos: position{line: 45, col: 14, offset: 811},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 45, col: 14, offset: 811},
						name: "__",
					},
					&oneOrMoreExpr{
						pos: position{line: 45, col: 17, offset: 814},
						expr: &ruleRefExpr{
							pos:  position{line: 45, col: 17, offset: 814},
							name: "Join",
						},
					},
				},
			},
		},
		{
			name: "Join",
			pos:  position{line: 46, col: 1, offset: 821},
			expr: &actionExpr{
				pos: position{line: 46, col: 10, offset: 832},
				run: (*parser).callonJoin1,
				expr: &seqExpr{
					pos: position{line: 46, col: 10, offset: 832},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 46, col: 10, offset: 832},
							val:        "join",
							ignoreCase: false,
							want:       "\"join\"",
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 17, offset: 839},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 20, offset: 842},
							label: "target",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 27, offset: 849},
								name: "JoinTarget",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 38, offset: 860},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 46, col: 41, offset: 863},
							val:        "on",
							ignoreCase: false,
							want:       "\"on\"",
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 47, offset: 869},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 50, offset: 872},
							label: "self",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 55, offset: 877},
								name: "MiltiLevelField",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 71, offset: 893},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 74, offset: 896},
							label: "compare",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 82, offset: 904},
								name: "CompareOp",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 92, offset: 914},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 95, offset: 917},
							label: "ref",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 99, offset: 921},
								name: "MiltiLevelField",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 115, offset: 937},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "JoinTarget",
			pos:  position{line: 50, col: 1, offset: 991},
			expr: &actionExpr{
				pos: position{line: 50, col: 14, offset: 1006},
				run: (*parser).callonJoinTarget1,
				expr: &seqExpr{
					pos: position{line: 50, col: 14, offset: 1006},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 50, col: 14, offset: 1006},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 20, offset: 1012},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 50, col: 33, offset: 1025},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 50, col: 36, offset: 1028},
							label: "alias",
							expr: &zeroOrOneExpr{
								pos: position{line: 50, col: 42, offset: 1034},
								expr: &seqExpr{
									pos: position{line: 50, col: 43, offset: 1035},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 50, col: 43, offset: 1035},
											val:        "as",
											ignoreCase: false,
											want:       "\"as\"",
										},
										&ruleRefExpr{
											pos:  position{line: 50, col: 48, offset: 1040},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 50, col: 51, offset: 1043},
											name: "Identifier",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "WhereClause",
			pos:  position{line: 55, col: 1, offset: 1099},
			expr: &seqExpr{
				pos: position{line: 55, col: 16, offset: 1116},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 55, col: 16, offset: 1116},
						val:        "where",
						ignoreCase: false,
						want:       "\"where\"",
					},
					&ruleRefExpr{
						pos:  position{line: 55, col: 24, offset: 1124},
						name: "__",
					},
					&ruleRefExpr{
						pos:  position{line: 55, col: 27, offset: 1127},
						name: "WhereList",
					},
				},
			},
		},
		{
			name: "WhereList",
			pos:  position{line: 56, col: 1, offset: 1138},
			expr: &actionExpr{
				pos: position{line: 56, col: 13, offset: 1152},
				run: (*parser).callonWhereList1,
				expr: &seqExpr{
					pos: position{line: 56, col: 13, offset: 1152},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 56, col: 13, offset: 1152},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 19, offset: 1158},
								name: "Where",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 56, col: 25, offset: 1164},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 56, col: 28, offset: 1167},
							label: "tails",
							expr: &zeroOrMoreExpr{
								pos: position{line: 56, col: 34, offset: 1173},
								expr: &ruleRefExpr{
									pos:  position{line: 56, col: 34, offset: 1173},
									name: "WhereTail",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "WhereTail",
			pos:  position{line: 59, col: 1, offset: 1225},
			expr: &actionExpr{
				pos: position{line: 59, col: 14, offset: 1240},
				run: (*parser).callonWhereTail1,
				expr: &seqExpr{
					pos: position{line: 59, col: 14, offset: 1240},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 59, col: 14, offset: 1240},
							label: "b",
							expr: &ruleRefExpr{
								pos:  position{line: 59, col: 16, offset: 1242},
								name: "BoolOP",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 59, col: 23, offset: 1249},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 59, col: 26, offset: 1252},
							label: "w",
							expr: &ruleRefExpr{
								pos:  position{line: 59, col: 28, offset: 1254},
								name: "Where",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 59, col: 34, offset: 1260},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "Where",
			pos:  position{line: 63, col: 1, offset: 1322},
			expr: &choiceExpr{
				pos: position{line: 63, col: 9, offset: 1332},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 63, col: 9, offset: 1332},
						name: "WhereCondition",
					},
					&ruleRefExpr{
						pos:  position{line: 63, col: 26, offset: 1349},
						name: "WhereHasBracket",
					},
				},
			},
		},
		{
			name: "WhereHasBracket",
			pos:  position{line: 64, col: 1, offset: 1365},
			expr: &seqExpr{
				pos: position{line: 64, col: 20, offset: 1386},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 64, col: 20, offset: 1386},
						val:        "(",
						ignoreCase: false,
						want:       "\"(\"",
					},
					&ruleRefExpr{
						pos:  position{line: 64, col: 24, offset: 1390},
						name: "__",
					},
					&ruleRefExpr{
						pos:  position{line: 64, col: 27, offset: 1393},
						name: "WhereList",
					},
					&ruleRefExpr{
						pos:  position{line: 64, col: 38, offset: 1404},
						name: "__",
					},
					&litMatcher{
						pos:        position{line: 64, col: 41, offset: 1407},
						val:        ")",
						ignoreCase: false,
						want:       "\")\"",
					},
				},
			},
		},
		{
			name: "WhereCondition",
			pos:  position{line: 65, col: 1, offset: 1412},
			expr: &actionExpr{
				pos: position{line: 65, col: 18, offset: 1431},
				run: (*parser).callonWhereCondition1,
				expr: &seqExpr{
					pos: position{line: 65, col: 18, offset: 1431},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 65, col: 18, offset: 1431},
							label: "field",
							expr: &ruleRefExpr{
								pos:  position{line: 65, col: 24, offset: 1437},
								name: "MiltiLevelField",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 65, col: 40, offset: 1453},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 65, col: 43, offset: 1456},
							label: "op",
							expr: &ruleRefExpr{
								pos:  position{line: 65, col: 46, offset: 1459},
								name: "CompareOp",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 65, col: 56, offset: 1469},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 65, col: 60, offset: 1473},
							label: "condition",
							expr: &ruleRefExpr{
								pos:  position{line: 65, col: 70, offset: 1483},
								name: "Condition",
							},
						},
					},
				},
			},
		},
		{
			name: "Condition",
			pos:  position{line: 70, col: 1, offset: 1549},
			expr: &choiceExpr{
				pos: position{line: 70, col: 13, offset: 1563},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 70, col: 13, offset: 1563},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 70, col: 22, offset: 1572},
						name: "Bool",
					},
					&ruleRefExpr{
						pos:  position{line: 70, col: 28, offset: 1578},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 70, col: 36, offset: 1586},
						name: "Null",
					},
					&ruleRefExpr{
						pos:  position{line: 70, col: 43, offset: 1593},
						name: "Ref",
					},
				},
			},
		},
		{
			name: "MiltiLevelField",
			pos:  position{line: 72, col: 1, offset: 1598},
			expr: &actionExpr{
				pos: position{line: 72, col: 21, offset: 1620},
				run: (*parser).callonMiltiLevelField1,
				expr: &labeledExpr{
					pos:   position{line: 72, col: 21, offset: 1620},
					label: "ident",
					expr: &seqExpr{
						pos: position{line: 72, col: 28, offset: 1627},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 72, col: 28, offset: 1627},
								name: "Identifier",
							},
							&zeroOrMoreExpr{
								pos: position{line: 72, col: 40, offset: 1639},
								expr: &seqExpr{
									pos: position{line: 72, col: 41, offset: 1640},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 72, col: 41, offset: 1640},
											val:        ".",
											ignoreCase: false,
											want:       "\".\"",
										},
										&ruleRefExpr{
											pos:  position{line: 72, col: 45, offset: 1644},
											name: "Identifier",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BoolOP",
			pos:  position{line: 76, col: 1, offset: 1698},
			expr: &choiceExpr{
				pos: position{line: 76, col: 11, offset: 1710},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 76, col: 11, offset: 1710},
						val:        "and",
						ignoreCase: false,
						want:       "\"and\"",
					},
					&litMatcher{
						pos:        position{line: 76, col: 18, offset: 1717},
						val:        "or",
						ignoreCase: false,
						want:       "\"or\"",
					},
					&actionExpr{
						pos: position{line: 76, col: 24, offset: 1723},
						run: (*parser).callonBoolOP4,
						expr: &litMatcher{
							pos:        position{line: 76, col: 24, offset: 1723},
							val:        "not",
							ignoreCase: false,
							want:       "\"not\"",
						},
					},
				},
			},
		},
		{
			name: "CompareOp",
			pos:  position{line: 79, col: 1, offset: 1769},
			expr: &choiceExpr{
				pos: position{line: 79, col: 15, offset: 1785},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 79, col: 15, offset: 1785},
						val:        "!=",
						ignoreCase: false,
						want:       "\"!=\"",
					},
					&litMatcher{
						pos:        position{line: 79, col: 21, offset: 1791},
						val:        "=",
						ignoreCase: false,
						want:       "\"=\"",
					},
					&litMatcher{
						pos:        position{line: 79, col: 26, offset: 1796},
						val:        "not in",
						ignoreCase: false,
						want:       "\"not in\"",
					},
					&actionExpr{
						pos: position{line: 79, col: 36, offset: 1806},
						run: (*parser).callonCompareOp5,
						expr: &litMatcher{
							pos:        position{line: 79, col: 36, offset: 1806},
							val:        "in",
							ignoreCase: false,
							want:       "\"in\"",
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 88, col: 1, offset: 1875},
			expr: &actionExpr{
				pos: position{line: 88, col: 10, offset: 1886},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 88, col: 10, offset: 1886},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 88, col: 10, offset: 1886},
							expr: &litMatcher{
								pos:        position{line: 88, col: 10, offset: 1886},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 88, col: 15, offset: 1891},
							name: "Integer",
						},
						&zeroOrOneExpr{
							pos: position{line: 88, col: 23, offset: 1899},
							expr: &seqExpr{
								pos: position{line: 88, col: 25, offset: 1901},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 88, col: 25, offset: 1901},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 88, col: 29, offset: 1905},
										expr: &ruleRefExpr{
											pos:  position{line: 88, col: 29, offset: 1905},
											name: "DecimalDigit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 88, col: 46, offset: 1922},
							expr: &ruleRefExpr{
								pos:  position{line: 88, col: 46, offset: 1922},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 95, col: 1, offset: 2103},
			expr: &choiceExpr{
				pos: position{line: 95, col: 11, offset: 2115},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 95, col: 11, offset: 2115},
						val:        "0",
						ignoreCase: false,
						want:       "\"0\"",
					},
					&seqExpr{
						pos: position{line: 95, col: 17, offset: 2121},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 95, col: 17, offset: 2121},
								name: "NonZeroDecimalDigit",
							},
							&zeroOrMoreExpr{
								pos: position{line: 95, col: 37, offset: 2141},
								expr: &ruleRefExpr{
									pos:  position{line: 95, col: 37, offset: 2141},
									name: "DecimalDigit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 97, col: 1, offset: 2156},
			expr: &seqExpr{
				pos: position{line: 97, col: 12, offset: 2169},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 97, col: 12, offset: 2169},
						val:        "e",
						ignoreCase: true,
						want:       "\"e\"i",
					},
					&zeroOrOneExpr{
						pos: position{line: 97, col: 17, offset: 2174},
						expr: &charClassMatcher{
							pos:        position{line: 97, col: 17, offset: 2174},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 97, col: 23, offset: 2180},
						expr: &ruleRefExpr{
							pos:  position{line: 97, col: 23, offset: 2180},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 99, col: 1, offset: 2195},
			expr: &actionExpr{
				pos: position{line: 99, col: 10, offset: 2206},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 99, col: 10, offset: 2206},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 99, col: 10, offset: 2206},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 99, col: 14, offset: 2210},
							expr: &choiceExpr{
								pos: position{line: 99, col: 16, offset: 2212},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 99, col: 16, offset: 2212},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 99, col: 16, offset: 2212},
												expr: &ruleRefExpr{
													pos:  position{line: 99, col: 17, offset: 2213},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 99, col: 29, offset: 2225,
											},
										},
									},
									&seqExpr{
										pos: position{line: 99, col: 33, offset: 2229},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 99, col: 33, offset: 2229},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 99, col: 38, offset: 2234},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 99, col: 56, offset: 2252},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 105, col: 1, offset: 2399},
			expr: &charClassMatcher{
				pos:        position{line: 105, col: 15, offset: 2415},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 107, col: 1, offset: 2431},
			expr: &choiceExpr{
				pos: position{line: 107, col: 18, offset: 2450},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 107, col: 18, offset: 2450},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 107, col: 37, offset: 2469},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 109, col: 1, offset: 2484},
			expr: &charClassMatcher{
				pos:        position{line: 109, col: 20, offset: 2505},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 111, col: 1, offset: 2518},
			expr: &seqExpr{
				pos: position{line: 111, col: 17, offset: 2536},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 111, col: 17, offset: 2536},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 111, col: 21, offset: 2540},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 111, col: 30, offset: 2549},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 111, col: 39, offset: 2558},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 111, col: 48, offset: 2567},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 113, col: 1, offset: 2577},
			expr: &charClassMatcher{
				pos:        position{line: 113, col: 16, offset: 2594},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 115, col: 1, offset: 2601},
			expr: &charClassMatcher{
				pos:        position{line: 115, col: 23, offset: 2625},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 117, col: 1, offset: 2632},
			expr: &charClassMatcher{
				pos:        position{line: 117, col: 12, offset: 2645},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Bool",
			pos:  position{line: 119, col: 1, offset: 2656},
			expr: &choiceExpr{
				pos: position{line: 119, col: 8, offset: 2665},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 119, col: 8, offset: 2665},
						run: (*parser).callonBool2,
						expr: &litMatcher{
							pos:        position{line: 119, col: 8, offset: 2665},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 119, col: 47, offset: 2704},
						run: (*parser).callonBool4,
						expr: &litMatcher{
							pos:        position{line: 119, col: 47, offset: 2704},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 121, col: 1, offset: 2744},
			expr: &actionExpr{
				pos: position{line: 121, col: 8, offset: 2753},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 121, col: 8, offset: 2753},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name: "Ref",
			pos:  position{line: 123, col: 1, offset: 2786},
			expr: &actionExpr{
				pos: position{line: 123, col: 8, offset: 2795},
				run: (*parser).callonRef1,
				expr: &seqExpr{
					pos: position{line: 123, col: 8, offset: 2795},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 123, col: 8, offset: 2795},
							val:        "$",
							ignoreCase: false,
							want:       "\"$\"",
						},
						&labeledExpr{
							pos:   position{line: 123, col: 12, offset: 2799},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 123, col: 17, offset: 2804},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "Keyword",
			pos:  position{line: 130, col: 1, offset: 2875},
			expr: &choiceExpr{
				pos: position{line: 130, col: 12, offset: 2888},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 130, col: 12, offset: 2888},
						name: "BoolOP",
					},
					&ruleRefExpr{
						pos:  position{line: 130, col: 20, offset: 2896},
						name: "CompareOp",
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 131, col: 1, offset: 2906},
			expr: &actionExpr{
				pos: position{line: 131, col: 14, offset: 2921},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 131, col: 14, offset: 2921},
					exprs: []interface{}{
						&notExpr{
							pos: position{line: 131, col: 14, offset: 2921},
							expr: &ruleRefExpr{
								pos:  position{line: 131, col: 15, offset: 2922},
								name: "Keyword",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 131, col: 23, offset: 2930},
							expr: &choiceExpr{
								pos: position{line: 131, col: 24, offset: 2931},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 131, col: 24, offset: 2931},
										name: "Letter",
									},
									&litMatcher{
										pos:        position{line: 131, col: 33, offset: 2940},
										val:        "_",
										ignoreCase: false,
										want:       "\"_\"",
									},
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 131, col: 39, offset: 2946},
							expr: &choiceExpr{
								pos: position{line: 131, col: 40, offset: 2947},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 131, col: 40, offset: 2947},
										name: "Letter",
									},
									&ruleRefExpr{
										pos:  position{line: 131, col: 49, offset: 2956},
										name: "Digit",
									},
									&charClassMatcher{
										pos:        position{line: 131, col: 57, offset: 2964},
										val:        "[_]",
										chars:      []rune{'_'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ListSeparator",
			pos:  position{line: 134, col: 1, offset: 3014},
			expr: &charClassMatcher{
				pos:        position{line: 134, col: 17, offset: 3032},
				val:        "[,;]",
				chars:      []rune{',', ';'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Letter",
			pos:  position{line: 135, col: 1, offset: 3037},
			expr: &charClassMatcher{
				pos:        position{line: 135, col: 10, offset: 3048},
				val:        "[A-Za-z]",
				ranges:     []rune{'A', 'Z', 'a', 'z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Digit",
			pos:  position{line: 136, col: 1, offset: 3057},
			expr: &charClassMatcher{
				pos:        position{line: 136, col: 9, offset: 3067},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "SourceChar",
			pos:  position{line: 139, col: 1, offset: 3075},
			expr: &anyMatcher{
				line: 139, col: 14, offset: 3090,
			},
		},
		{
			name: "Comment",
			pos:  position{line: 140, col: 1, offset: 3092},
			expr: &choiceExpr{
				pos: position{line: 140, col: 11, offset: 3104},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 140, col: 11, offset: 3104},
						name: "MultiLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 140, col: 30, offset: 3123},
						name: "SingleLineComment",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 141, col: 1, offset: 3141},
			expr: &seqExpr{
				pos: position{line: 141, col: 20, offset: 3162},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 141, col: 20, offset: 3162},
						val:        "/*",
						ignoreCase: false,
						want:       "\"/*\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 141, col: 25, offset: 3167},
						expr: &seqExpr{
							pos: position{line: 141, col: 27, offset: 3169},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 141, col: 27, offset: 3169},
									expr: &litMatcher{
										pos:        position{line: 141, col: 28, offset: 3170},
										val:        "*/",
										ignoreCase: false,
										want:       "\"*/\"",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 141, col: 33, offset: 3175},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 141, col: 47, offset: 3189},
						val:        "*/",
						ignoreCase: false,
						want:       "\"*/\"",
					},
				},
			},
		},
		{
			name: "MultiLineCommentNoLineTerminator",
			pos:  position{line: 142, col: 1, offset: 3194},
			expr: &seqExpr{
				pos: position{line: 142, col: 36, offset: 3231},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 142, col: 36, offset: 3231},
						val:        "/*",
						ignoreCase: false,
						want:       "\"/*\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 142, col: 41, offset: 3236},
						expr: &seqExpr{
							pos: position{line: 142, col: 43, offset: 3238},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 142, col: 43, offset: 3238},
									expr: &choiceExpr{
										pos: position{line: 142, col: 46, offset: 3241},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 142, col: 46, offset: 3241},
												val:        "*/",
												ignoreCase: false,
												want:       "\"*/\"",
											},
											&ruleRefExpr{
												pos:  position{line: 142, col: 53, offset: 3248},
												name: "EOL",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 142, col: 59, offset: 3254},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 142, col: 73, offset: 3268},
						val:        "*/",
						ignoreCase: false,
						want:       "\"*/\"",
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 143, col: 1, offset: 3273},
			expr: &choiceExpr{
				pos: position{line: 143, col: 21, offset: 3295},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 143, col: 22, offset: 3296},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 143, col: 22, offset: 3296},
								val:        "//",
								ignoreCase: false,
								want:       "\"//\"",
							},
							&zeroOrMoreExpr{
								pos: position{line: 143, col: 27, offset: 3301},
								expr: &seqExpr{
									pos: position{line: 143, col: 29, offset: 3303},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 143, col: 29, offset: 3303},
											expr: &ruleRefExpr{
												pos:  position{line: 143, col: 30, offset: 3304},
												name: "EOL",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 143, col: 34, offset: 3308},
											name: "SourceChar",
										},
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 143, col: 52, offset: 3326},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 143, col: 52, offset: 3326},
								val:        "#",
								ignoreCase: false,
								want:       "\"#\"",
							},
							&zeroOrMoreExpr{
								pos: position{line: 143, col: 56, offset: 3330},
								expr: &seqExpr{
									pos: position{line: 143, col: 58, offset: 3332},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 143, col: 58, offset: 3332},
											expr: &ruleRefExpr{
												pos:  position{line: 143, col: 59, offset: 3333},
												name: "EOL",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 143, col: 63, offset: 3337},
											name: "SourceChar",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 146, col: 1, offset: 3354},
			expr: &zeroOrMoreExpr{
				pos: position{line: 146, col: 6, offset: 3361},
				expr: &choiceExpr{
					pos: position{line: 146, col: 8, offset: 3363},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 146, col: 8, offset: 3363},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 146, col: 21, offset: 3376},
							name: "EOL",
						},
						&ruleRefExpr{
							pos:  position{line: 146, col: 27, offset: 3382},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "NoCommentIgnore",
			pos:  position{line: 147, col: 1, offset: 3393},
			expr: &zeroOrMoreExpr{
				pos: position{line: 147, col: 19, offset: 3413},
				expr: &choiceExpr{
					pos: position{line: 147, col: 21, offset: 3415},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 147, col: 21, offset: 3415},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 147, col: 34, offset: 3428},
							name: "EOL",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 148, col: 1, offset: 3435},
			expr: &zeroOrMoreExpr{
				pos: position{line: 148, col: 5, offset: 3441},
				expr: &ruleRefExpr{
					pos:  position{line: 148, col: 6, offset: 3442},
					name: "Whitespace",
				},
			},
		},
		{
			name: "WS",
			pos:  position{line: 149, col: 1, offset: 3455},
			expr: &zeroOrMoreExpr{
				pos: position{line: 149, col: 6, offset: 3462},
				expr: &ruleRefExpr{
					pos:  position{line: 149, col: 6, offset: 3462},
					name: "Whitespace",
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 151, col: 1, offset: 3475},
			expr: &charClassMatcher{
				pos:        position{line: 151, col: 14, offset: 3490},
				val:        "[ \\t\\r]",
				chars:      []rune{' ', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 152, col: 1, offset: 3498},
			expr: &litMatcher{
				pos:        position{line: 152, col: 7, offset: 3506},
				val:        "\n",
				ignoreCase: false,
				want:       "\"\\n\"",
			},
		},
		{
			name: "EOS",
			pos:  position{line: 153, col: 1, offset: 3511},
			expr: &choiceExpr{
				pos: position{line: 153, col: 7, offset: 3519},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 153, col: 7, offset: 3519},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 153, col: 7, offset: 3519},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 153, col: 10, offset: 3522},
								val:        ";",
								ignoreCase: false,
								want:       "\";\"",
							},
						},
					},
					&seqExpr{
						pos: position{line: 153, col: 16, offset: 3528},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 153, col: 16, offset: 3528},
								name: "_",
							},
							&zeroOrOneExpr{
								pos: position{line: 153, col: 18, offset: 3530},
								expr: &ruleRefExpr{
									pos:  position{line: 153, col: 18, offset: 3530},
									name: "SingleLineComment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 153, col: 37, offset: 3549},
								name: "EOL",
							},
						},
					},
					&seqExpr{
						pos: position{line: 153, col: 43, offset: 3555},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 153, col: 43, offset: 3555},
								name: "__",
							},
							&ruleRefExpr{
								pos:  position{line: 153, col: 46, offset: 3558},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 155, col: 1, offset: 3563},
			expr: &notExpr{
				pos: position{line: 155, col: 7, offset: 3571},
				expr: &anyMatcher{
					line: 155, col: 8, offset: 3572,
				},
			},
		},
		{
			name: "SyntaxError",
			pos:  position{line: 158, col: 1, offset: 3576},
			expr: &actionExpr{
				pos: position{line: 158, col: 15, offset: 3592},
				run: (*parser).callonSyntaxError1,
				expr: &anyMatcher{
					line: 158, col: 15, offset: 3592,
				},
			},
		},
	},
}

func (c *current) onGrammar1(statements interface{}) (interface{}, error) {
	return parseCompile(statements)
}

func (p *parser) callonGrammar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGrammar1(stack["statements"])
}

func (c *current) onModelDefine1(ident, selectData interface{}) (interface{}, error) {
	return parseModel(ident, selectData)
}

func (p *parser) callonModelDefine1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onModelDefine1(stack["ident"], stack["selectData"])
}

func (c *current) onSelect1(fieldList, model, join, where interface{}) (interface{}, error) {
	return parseSelectStmt(fieldList, model, join, where)
}

func (p *parser) callonSelect1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelect1(stack["fieldList"], stack["model"], stack["join"], stack["where"])
}

func (c *current) onSelectField1(name, alias interface{}) (interface{}, error) {
	return parseSelectField(name, alias)
}

func (p *parser) callonSelectField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelectField1(stack["name"], stack["alias"])
}

func (c *current) onJoin1(target, self, compare, ref interface{}) (interface{}, error) {
	return parseJoin(target, self, compare, ref)
}

func (p *parser) callonJoin1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJoin1(stack["target"], stack["self"], stack["compare"], stack["ref"])
}

func (c *current) onJoinTarget1(name, alias interface{}) (interface{}, error) {
	return parseJoinTarget(name, alias)
}

func (p *parser) callonJoinTarget1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onJoinTarget1(stack["name"], stack["alias"])
}

func (c *current) onWhereList1(first, tails interface{}) (interface{}, error) {
	return parseWhereList(first, tails)
}

func (p *parser) callonWhereList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWhereList1(stack["first"], stack["tails"])
}

func (c *current) onWhereTail1(b, w interface{}) (interface{}, error) {
	return []interface{}{BoolOp(parseString(b)), w}, nil
}

func (p *parser) callonWhereTail1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWhereTail1(stack["b"], stack["w"])
}

func (c *current) onWhereCondition1(field, op, condition interface{}) (interface{}, error) {
	return parseWhereCondition(field, op, condition)
}

func (p *parser) callonWhereCondition1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWhereCondition1(stack["field"], stack["op"], stack["condition"])
}

func (c *current) onMiltiLevelField1(ident interface{}) (interface{}, error) {
	return parseMiltiLevelField(ident)
}

func (p *parser) callonMiltiLevelField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMiltiLevelField1(stack["ident"])
}

func (c *current) onBoolOP4() (interface{}, error) {
	return BoolOp(string(c.text)), nil
}

func (p *parser) callonBoolOP4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolOP4()
}

func (c *current) onCompareOp5() (interface{}, error) {
	return CompareOp(string(c.text)), nil
}

func (p *parser) callonCompareOp5() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCompareOp5()
}

func (c *current) onNumber1() (interface{}, error) {
	// JSON numbers have the same syntax as Go's, and are parseable using
	// strconv.
	r, err := strconv.ParseFloat(string(c.text), 64)
	return Number(r), err
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onString1() (interface{}, error) {
	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	r, err := strconv.Unquote(string(c.text))
	return StringObj(r), err
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onBool2() (interface{}, error) {
	return Boolean(true), nil
}

func (p *parser) callonBool2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool2()
}

func (c *current) onBool4() (interface{}, error) {
	return Boolean(false), nil
}

func (p *parser) callonBool4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool4()
}

func (c *current) onNull1() (interface{}, error) {
	return None(0), nil
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) onRef1(name interface{}) (interface{}, error) {
	return Ref(parseString(name)), nil
}

func (p *parser) callonRef1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRef1(stack["name"])
}

func (c *current) onIdentifier1() (interface{}, error) {
	return Identifier(string(c.text)), nil
}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onSyntaxError1() (interface{}, error) {
	return nil, errors.New("parser: syntax error")
}

func (p *parser) callonSyntaxError1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSyntaxError1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
